/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.java.com.mycompany.sigeliapp.vistas;


/**
 *
 * @author Eduar Xavier
 */
public class Configuracion extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    
    public Configuracion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDocumentoRegistro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JLabel();
        txtNombreRegistro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEmailRegistro = new javax.swing.JTextField();
        txtcarrera = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        carrera = new javax.swing.JLabel();
        txtClaveRegistro1 = new javax.swing.JPasswordField();
        txtTelefonoRegistro = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtClaveRegistro = new javax.swing.JPasswordField();
        btnRegistro = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Configuración");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Documento");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        txtDocumentoRegistro.setEditable(false);
        txtDocumentoRegistro.setBackground(new java.awt.Color(249, 249, 249));
        txtDocumentoRegistro.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(txtDocumentoRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 230, 30));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Nombre completo");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        btnVolver.setForeground(new java.awt.Color(51, 51, 51));
        btnVolver.setText("< Volver");
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        txtNombreRegistro.setEditable(false);
        txtNombreRegistro.setBackground(new java.awt.Color(249, 249, 249));
        txtNombreRegistro.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(txtNombreRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 230, 30));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Email");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        txtEmailRegistro.setEditable(false);
        txtEmailRegistro.setBackground(new java.awt.Color(249, 249, 249));
        txtEmailRegistro.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(txtEmailRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 230, 30));

        txtcarrera.setEditable(false);
        txtcarrera.setBackground(new java.awt.Color(249, 249, 249));
        txtcarrera.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(txtcarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 230, 30));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Telefono");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        carrera.setBackground(new java.awt.Color(0, 0, 0));
        carrera.setForeground(new java.awt.Color(0, 0, 0));
        carrera.setText("Carrera");
        getContentPane().add(carrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        txtClaveRegistro1.setBackground(new java.awt.Color(249, 249, 249));
        txtClaveRegistro1.setForeground(new java.awt.Color(51, 51, 51));
        txtClaveRegistro1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtClaveRegistro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 230, 30));

        txtTelefonoRegistro.setEditable(false);
        txtTelefonoRegistro.setBackground(new java.awt.Color(249, 249, 249));
        txtTelefonoRegistro.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(txtTelefonoRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 196, 230, 30));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Contraseña");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Repita su contraseña");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, -1, -1));

        txtClaveRegistro.setBackground(new java.awt.Color(249, 249, 249));
        txtClaveRegistro.setForeground(new java.awt.Color(51, 51, 51));
        txtClaveRegistro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtClaveRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 230, 30));

        btnRegistro.setBackground(new java.awt.Color(255, 51, 51));
        btnRegistro.setForeground(new java.awt.Color(204, 204, 204));
        btnRegistro.setText("Cambiar clave");
        btnRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, 110, 30));

        btnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelar.setForeground(new java.awt.Color(51, 51, 51));
        btnCancelar.setText("Cancelar");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 110, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Eduar Xavier\\Desktop\\EduarXavier\\sigeli\\Sigeli\\src\\main\\java\\main\\java\\com\\mycompany\\sigeliapp\\vistas\\imagenes\\interfazRegistro.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Configuracion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnRegistro;
    public javax.swing.JLabel btnVolver;
    public javax.swing.JLabel carrera;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JSlider jSlider1;
    public javax.swing.JPasswordField txtClaveRegistro;
    public javax.swing.JPasswordField txtClaveRegistro1;
    public javax.swing.JTextField txtDocumentoRegistro;
    public javax.swing.JTextField txtEmailRegistro;
    public javax.swing.JTextField txtNombreRegistro;
    public javax.swing.JTextField txtTelefonoRegistro;
    public javax.swing.JTextField txtcarrera;
    // End of variables declaration//GEN-END:variables
}
