/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.java.com.mycompany.sigeliapp.vistas;

/**
 *
 * @author Eduar Xavier
 */
public class PanelEstudiante extends javax.swing.JFrame {

    /**
     * Creates new form panelAdminLibros
     */
    public PanelEstudiante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        panel4 = new javax.swing.JPanel();
        txtNombreLibro4 = new javax.swing.JLabel();
        txtNombreAutor4 = new javax.swing.JLabel();
        txtEstanteLibro4 = new javax.swing.JLabel();
        txtFilaLibro4 = new javax.swing.JLabel();
        txtDisponibilidadLibro4 = new javax.swing.JLabel();
        txtAnoLibro4 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        panel5 = new javax.swing.JPanel();
        txtNombreLibro5 = new javax.swing.JLabel();
        txtNombreAutor5 = new javax.swing.JLabel();
        txtEstanteLibro5 = new javax.swing.JLabel();
        txtFilaLibro5 = new javax.swing.JLabel();
        txtDisponibilidadLibro5 = new javax.swing.JLabel();
        txtAnoLibro5 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        backPagAdmin = new javax.swing.JButton();
        panel2 = new javax.swing.JPanel();
        txtNombreLibro2 = new javax.swing.JLabel();
        txtNombreAutor2 = new javax.swing.JLabel();
        txtEstanteLibro2 = new javax.swing.JLabel();
        txtFilaLibro2 = new javax.swing.JLabel();
        txtDisponibilidadLibro2 = new javax.swing.JLabel();
        txtAnoLibro2 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        txtCantLibroAdmin = new javax.swing.JLabel();
        iconNotificacion = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JLabel();
        panel1 = new javax.swing.JPanel();
        txtNombreLibro1 = new javax.swing.JLabel();
        txtNombreAutor1 = new javax.swing.JLabel();
        txtEstanteLibro1 = new javax.swing.JLabel();
        txtFilaLibro1 = new javax.swing.JLabel();
        txtDisponibilidadLibro1 = new javax.swing.JLabel();
        txtAnoLibro1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txtBusquedaAdmin = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNotificaciones = new javax.swing.JTextPane();
        nextPagAdmin = new javax.swing.JButton();
        panel3 = new javax.swing.JPanel();
        txtNombreLibro3 = new javax.swing.JLabel();
        txtNombreAutor3 = new javax.swing.JLabel();
        txtEstanteLibro3 = new javax.swing.JLabel();
        txtFilaLibro3 = new javax.swing.JLabel();
        txtDisponibilidadLibro3 = new javax.swing.JLabel();
        txtAnoLibro3 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        btnPegar = new javax.swing.JButton();
        btnBusqueda = new javax.swing.JButton();
        txtIngresoBusqueda = new javax.swing.JTextField();
        btnOpcionesPanelAdmin = new javax.swing.JLabel();
        txtNombrePersona = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel4.setBackground(new java.awt.Color(249, 249, 249));
        panel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 2));
        panel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtNombreLibro4.setForeground(new java.awt.Color(51, 51, 51));
        txtNombreLibro4.setText("jLabel3");

        txtNombreAutor4.setForeground(new java.awt.Color(51, 51, 51));
        txtNombreAutor4.setText("jLabel4");

        txtEstanteLibro4.setForeground(new java.awt.Color(51, 51, 51));
        txtEstanteLibro4.setText("jLabel5");

        txtFilaLibro4.setForeground(new java.awt.Color(51, 51, 51));
        txtFilaLibro4.setText("jLabel6");

        txtDisponibilidadLibro4.setForeground(new java.awt.Color(51, 51, 51));
        txtDisponibilidadLibro4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtDisponibilidadLibro4.setText("jLabel7");

        txtAnoLibro4.setForeground(new java.awt.Color(51, 51, 51));
        txtAnoLibro4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAnoLibro4.setText("jLabel8");

        jSeparator6.setBackground(new java.awt.Color(153, 0, 0));
        jSeparator6.setForeground(new java.awt.Color(153, 0, 0));
        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout panel4Layout = new javax.swing.GroupLayout(panel4);
        panel4.setLayout(panel4Layout);
        panel4Layout.setHorizontalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombreLibro4, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                    .addComponent(txtNombreAutor4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(74, 74, 74)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDisponibilidadLibro4, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(txtAnoLibro4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEstanteLibro4)
                    .addComponent(txtFilaLibro4))
                .addGap(20, 20, 20))
        );
        panel4Layout.setVerticalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addComponent(txtNombreLibro4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreAutor4))
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDisponibilidadLibro4)
                            .addComponent(txtEstanteLibro4))
                        .addGap(14, 14, 14)
                        .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFilaLibro4)
                            .addComponent(txtAnoLibro4)))
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        getContentPane().add(panel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 660, -1));

        panel5.setBackground(new java.awt.Color(249, 249, 249));
        panel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 2));
        panel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtNombreLibro5.setForeground(new java.awt.Color(51, 51, 51));
        txtNombreLibro5.setText("jLabel3");

        txtNombreAutor5.setForeground(new java.awt.Color(51, 51, 51));
        txtNombreAutor5.setText("jLabel4");

        txtEstanteLibro5.setForeground(new java.awt.Color(51, 51, 51));
        txtEstanteLibro5.setText("jLabel5");

        txtFilaLibro5.setForeground(new java.awt.Color(51, 51, 51));
        txtFilaLibro5.setText("jLabel6");

        txtDisponibilidadLibro5.setForeground(new java.awt.Color(51, 51, 51));
        txtDisponibilidadLibro5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtDisponibilidadLibro5.setText("jLabel7");

        txtAnoLibro5.setForeground(new java.awt.Color(51, 51, 51));
        txtAnoLibro5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAnoLibro5.setText("jLabel8");

        jSeparator7.setBackground(new java.awt.Color(153, 0, 0));
        jSeparator7.setForeground(new java.awt.Color(153, 0, 0));
        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout panel5Layout = new javax.swing.GroupLayout(panel5);
        panel5.setLayout(panel5Layout);
        panel5Layout.setHorizontalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombreLibro5, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                    .addComponent(txtNombreAutor5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(67, 67, 67)
                .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDisponibilidadLibro5, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(txtAnoLibro5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEstanteLibro5)
                    .addComponent(txtFilaLibro5))
                .addGap(20, 20, 20))
        );
        panel5Layout.setVerticalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel5Layout.createSequentialGroup()
                        .addComponent(txtNombreLibro5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreAutor5))
                    .addGroup(panel5Layout.createSequentialGroup()
                        .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDisponibilidadLibro5)
                            .addComponent(txtEstanteLibro5))
                        .addGap(14, 14, 14)
                        .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFilaLibro5)
                            .addComponent(txtAnoLibro5)))
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        getContentPane().add(panel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, 660, -1));

        backPagAdmin.setBackground(new java.awt.Color(249, 249, 249));
        backPagAdmin.setIcon(new javax.swing.ImageIcon("C:\\Users\\Eduar Xavier\\Desktop\\EduarXavier\\sigeli\\Sigeli\\src\\main\\java\\main\\java\\com\\mycompany\\sigeliapp\\vistas\\iconos\\iconoBefore.png")); // NOI18N
        backPagAdmin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249, 249, 249)));
        backPagAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backPagAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backPagAdminActionPerformed(evt);
            }
        });
        getContentPane().add(backPagAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 560, 150, 50));

        panel2.setBackground(new java.awt.Color(249, 249, 249));
        panel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 2));
        panel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtNombreLibro2.setForeground(new java.awt.Color(51, 51, 51));
        txtNombreLibro2.setText("jLabel3");

        txtNombreAutor2.setForeground(new java.awt.Color(51, 51, 51));
        txtNombreAutor2.setText("jLabel4");

        txtEstanteLibro2.setForeground(new java.awt.Color(51, 51, 51));
        txtEstanteLibro2.setText("jLabel5");

        txtFilaLibro2.setForeground(new java.awt.Color(51, 51, 51));
        txtFilaLibro2.setText("jLabel6");

        txtDisponibilidadLibro2.setForeground(new java.awt.Color(51, 51, 51));
        txtDisponibilidadLibro2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtDisponibilidadLibro2.setText("jLabel7");

        txtAnoLibro2.setForeground(new java.awt.Color(51, 51, 51));
        txtAnoLibro2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAnoLibro2.setText("jLabel8");

        jSeparator4.setBackground(new java.awt.Color(153, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(153, 0, 0));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombreLibro2, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                    .addComponent(txtNombreAutor2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(74, 74, 74)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDisponibilidadLibro2, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(txtAnoLibro2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEstanteLibro2)
                    .addComponent(txtFilaLibro2))
                .addGap(20, 20, 20))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addComponent(txtNombreLibro2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreAutor2))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDisponibilidadLibro2)
                            .addComponent(txtEstanteLibro2))
                        .addGap(14, 14, 14)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFilaLibro2)
                            .addComponent(txtAnoLibro2)))
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        getContentPane().add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 660, -1));

        txtCantLibroAdmin.setForeground(new java.awt.Color(51, 51, 51));
        txtCantLibroAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCantLibroAdmin.setText("jLabel2");
        getContentPane().add(txtCantLibroAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 580, 350, -1));

        iconNotificacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconNotificacion.setIcon(new javax.swing.ImageIcon("C:\\Users\\Eduar Xavier\\Desktop\\EduarXavier\\sigeli\\Sigeli\\src\\main\\java\\main\\java\\com\\mycompany\\sigeliapp\\vistas\\iconos\\iconoNotificacion.png")); // NOI18N
        iconNotificacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconNotificacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconNotificacionMouseClicked(evt);
            }
        });
        getContentPane().add(iconNotificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 170, -1));

        btnCerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon("C:\\Users\\Eduar Xavier\\Desktop\\EduarXavier\\sigeli\\Sigeli\\src\\main\\java\\main\\java\\com\\mycompany\\sigeliapp\\vistas\\iconos\\logout.png")); // NOI18N
        btnCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 190, -1));

        panel1.setBackground(new java.awt.Color(249, 249, 249));
        panel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 2));
        panel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtNombreLibro1.setForeground(new java.awt.Color(51, 51, 51));
        txtNombreLibro1.setText("jLabel3");

        txtNombreAutor1.setForeground(new java.awt.Color(51, 51, 51));
        txtNombreAutor1.setText("jLabel4");

        txtEstanteLibro1.setForeground(new java.awt.Color(51, 51, 51));
        txtEstanteLibro1.setText("jLabel5");

        txtFilaLibro1.setForeground(new java.awt.Color(51, 51, 51));
        txtFilaLibro1.setText("jLabel6");

        txtDisponibilidadLibro1.setForeground(new java.awt.Color(51, 51, 51));
        txtDisponibilidadLibro1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtDisponibilidadLibro1.setText("jLabel7");

        txtAnoLibro1.setForeground(new java.awt.Color(51, 51, 51));
        txtAnoLibro1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAnoLibro1.setText("jLabel8");

        jSeparator3.setBackground(new java.awt.Color(153, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(153, 0, 0));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombreLibro1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                    .addComponent(txtNombreAutor1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDisponibilidadLibro1, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(txtAnoLibro1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEstanteLibro1)
                    .addComponent(txtFilaLibro1))
                .addGap(20, 20, 20))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreLibro1)
                            .addComponent(txtDisponibilidadLibro1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreAutor1))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(txtEstanteLibro1)
                        .addGap(14, 14, 14)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFilaLibro1)
                            .addComponent(txtAnoLibro1)))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 660, 70));

        txtBusquedaAdmin.setForeground(new java.awt.Color(51, 51, 51));
        txtBusquedaAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtBusquedaAdmin.setText("jLabel1");
        getContentPane().add(txtBusquedaAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 650, -1));

        txtNotificaciones.setEditable(false);
        txtNotificaciones.setBackground(new java.awt.Color(116, 0, 0));
        txtNotificaciones.setForeground(new java.awt.Color(255, 255, 255));
        txtNotificaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(txtNotificaciones);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 170, 210));

        nextPagAdmin.setBackground(new java.awt.Color(249, 249, 249));
        nextPagAdmin.setIcon(new javax.swing.ImageIcon("C:\\Users\\Eduar Xavier\\Desktop\\EduarXavier\\sigeli\\Sigeli\\src\\main\\java\\main\\java\\com\\mycompany\\sigeliapp\\vistas\\iconos\\iconoNext.png")); // NOI18N
        nextPagAdmin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249, 249, 249)));
        nextPagAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nextPagAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextPagAdminActionPerformed(evt);
            }
        });
        getContentPane().add(nextPagAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 560, 150, 50));

        panel3.setBackground(new java.awt.Color(249, 249, 249));
        panel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 2));
        panel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtNombreLibro3.setForeground(new java.awt.Color(51, 51, 51));
        txtNombreLibro3.setText("jLabel3");

        txtNombreAutor3.setForeground(new java.awt.Color(51, 51, 51));
        txtNombreAutor3.setText("jLabel4");

        txtEstanteLibro3.setForeground(new java.awt.Color(51, 51, 51));
        txtEstanteLibro3.setText("jLabel5");

        txtFilaLibro3.setForeground(new java.awt.Color(51, 51, 51));
        txtFilaLibro3.setText("jLabel6");

        txtDisponibilidadLibro3.setForeground(new java.awt.Color(51, 51, 51));
        txtDisponibilidadLibro3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtDisponibilidadLibro3.setText("jLabel7");

        txtAnoLibro3.setForeground(new java.awt.Color(51, 51, 51));
        txtAnoLibro3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAnoLibro3.setText("jLabel8");

        jSeparator5.setBackground(new java.awt.Color(153, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(153, 0, 0));
        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombreLibro3, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                    .addComponent(txtNombreAutor3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(74, 74, 74)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDisponibilidadLibro3, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(txtAnoLibro3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEstanteLibro3)
                    .addComponent(txtFilaLibro3))
                .addGap(20, 20, 20))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addComponent(txtNombreLibro3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreAutor3))
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDisponibilidadLibro3)
                            .addComponent(txtEstanteLibro3))
                        .addGap(14, 14, 14)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFilaLibro3)
                            .addComponent(txtAnoLibro3)))
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        getContentPane().add(panel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 660, -1));

        btnPegar.setBackground(new java.awt.Color(204, 204, 204));
        btnPegar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Eduar Xavier\\Desktop\\EduarXavier\\sigeli\\Sigeli\\src\\main\\java\\main\\java\\com\\mycompany\\sigeliapp\\vistas\\iconos\\inconoPegar.png")); // NOI18N
        btnPegar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPegarActionPerformed(evt);
            }
        });
        getContentPane().add(btnPegar, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 50, 40, 30));

        btnBusqueda.setIcon(new javax.swing.ImageIcon("C:\\Users\\Eduar Xavier\\Desktop\\EduarXavier\\sigeli\\Sigeli\\src\\main\\java\\main\\java\\com\\mycompany\\sigeliapp\\vistas\\iconos\\iconoLupaBusqueda.png")); // NOI18N
        btnBusqueda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusquedaActionPerformed(evt);
            }
        });
        getContentPane().add(btnBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 50, 40, 30));

        txtIngresoBusqueda.setBackground(new java.awt.Color(153, 153, 153));
        txtIngresoBusqueda.setForeground(new java.awt.Color(51, 51, 51));
        txtIngresoBusqueda.setBorder(null);
        getContentPane().add(txtIngresoBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 580, 30));

        btnOpcionesPanelAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnOpcionesPanelAdmin.setIcon(new javax.swing.ImageIcon("C:\\Users\\Eduar Xavier\\Desktop\\EduarXavier\\sigeli\\Sigeli\\src\\main\\java\\main\\java\\com\\mycompany\\sigeliapp\\vistas\\iconos\\iconoUsuario.png")); // NOI18N
        btnOpcionesPanelAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btnOpcionesPanelAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 190, 50));

        txtNombrePersona.setBackground(new java.awt.Color(204, 204, 204));
        txtNombrePersona.setForeground(new java.awt.Color(204, 204, 204));
        txtNombrePersona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNombrePersona.setText("jLabel1");
        getContentPane().add(txtNombrePersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 190, -1));

        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Los libros pueden ser filtrados por nombre, Isbn, Autor o categorias especificas");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Eduar Xavier\\Desktop\\EduarXavier\\sigeli\\Sigeli\\src\\main\\java\\main\\java\\com\\mycompany\\sigeliapp\\vistas\\imagenes\\panelEstudiante.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPegarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPegarActionPerformed

    private void backPagAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backPagAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backPagAdminActionPerformed

    private void nextPagAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextPagAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nextPagAdminActionPerformed

    private void btnBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBusquedaActionPerformed

    private void iconNotificacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconNotificacionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_iconNotificacionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelEstudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton backPagAdmin;
    public javax.swing.JButton btnBusqueda;
    public javax.swing.JLabel btnCerrarSesion;
    public javax.swing.JLabel btnOpcionesPanelAdmin;
    public javax.swing.JButton btnPegar;
    public javax.swing.JLabel iconNotificacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JToggleButton jToggleButton1;
    public javax.swing.JButton nextPagAdmin;
    public javax.swing.JPanel panel1;
    public javax.swing.JPanel panel2;
    public javax.swing.JPanel panel3;
    public javax.swing.JPanel panel4;
    public javax.swing.JPanel panel5;
    public javax.swing.JLabel txtAnoLibro1;
    public javax.swing.JLabel txtAnoLibro2;
    public javax.swing.JLabel txtAnoLibro3;
    public javax.swing.JLabel txtAnoLibro4;
    public javax.swing.JLabel txtAnoLibro5;
    public javax.swing.JLabel txtBusquedaAdmin;
    public javax.swing.JLabel txtCantLibroAdmin;
    public javax.swing.JLabel txtDisponibilidadLibro1;
    public javax.swing.JLabel txtDisponibilidadLibro2;
    public javax.swing.JLabel txtDisponibilidadLibro3;
    public javax.swing.JLabel txtDisponibilidadLibro4;
    public javax.swing.JLabel txtDisponibilidadLibro5;
    public javax.swing.JLabel txtEstanteLibro1;
    public javax.swing.JLabel txtEstanteLibro2;
    public javax.swing.JLabel txtEstanteLibro3;
    public javax.swing.JLabel txtEstanteLibro4;
    public javax.swing.JLabel txtEstanteLibro5;
    public javax.swing.JLabel txtFilaLibro1;
    public javax.swing.JLabel txtFilaLibro2;
    public javax.swing.JLabel txtFilaLibro3;
    public javax.swing.JLabel txtFilaLibro4;
    public javax.swing.JLabel txtFilaLibro5;
    public javax.swing.JTextField txtIngresoBusqueda;
    public javax.swing.JLabel txtNombreAutor1;
    public javax.swing.JLabel txtNombreAutor2;
    public javax.swing.JLabel txtNombreAutor3;
    public javax.swing.JLabel txtNombreAutor4;
    public javax.swing.JLabel txtNombreAutor5;
    public javax.swing.JLabel txtNombreLibro1;
    public javax.swing.JLabel txtNombreLibro2;
    public javax.swing.JLabel txtNombreLibro3;
    public javax.swing.JLabel txtNombreLibro4;
    public javax.swing.JLabel txtNombreLibro5;
    public javax.swing.JLabel txtNombrePersona;
    public javax.swing.JTextPane txtNotificaciones;
    // End of variables declaration//GEN-END:variables
}
