/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.java.com.mycompany.sigeliapp.vistas;

/**
 *
 * @author Eduar Xavier
 */
public class PanelAddLibro extends javax.swing.JFrame {

    /**
     * Creates new form PanelVistaLibro
     */
    public PanelAddLibro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        panelExten = new javax.swing.JPanel();
        btnOpcionesPanelAdmin1 = new javax.swing.JLabel();
        txtNombrePersona1 = new javax.swing.JLabel();
        btnExtenPanelOff = new javax.swing.JLabel();
        adminLibros = new javax.swing.JLabel();
        addLibros = new javax.swing.JLabel();
        adminUsuarios = new javax.swing.JLabel();
        prestamos = new javax.swing.JLabel();
        multas = new javax.swing.JLabel();
        reportes = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JLabel();
        btnVolverMenu = new javax.swing.JLabel();
        txtNombrePersona = new javax.swing.JLabel();
        btnExtenPanel = new javax.swing.JLabel();
        btnOpcionesPanelAdmin = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtFila = new javax.swing.JTextField();
        txtEstante = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtAno = new javax.swing.JTextField();
        txtNombreLibro = new javax.swing.JTextField();
        txtEdicion = new javax.swing.JTextField();
        txtAutor = new javax.swing.JTextField();
        txtIsbn = new javax.swing.JTextField();
        btnAddlibro = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCarreraTxt = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Eduar Xavier\\Desktop\\EduarXavier\\sigeli\\Sigeli\\src\\main\\java\\main\\java\\com\\mycompany\\sigeliapp\\vistas\\iconos\\inconoCopiar.png")); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelExten.setBackground(new java.awt.Color(126, 0, 0));

        btnOpcionesPanelAdmin1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Eduar Xavier\\Desktop\\EduarXavier\\sigeli\\Sigeli\\src\\main\\java\\main\\java\\com\\mycompany\\sigeliapp\\vistas\\iconos\\iconoUsuario.png")); // NOI18N
        btnOpcionesPanelAdmin1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtNombrePersona1.setBackground(new java.awt.Color(204, 204, 204));
        txtNombrePersona1.setForeground(java.awt.Color.white);
        txtNombrePersona1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNombrePersona1.setText("jLabel1");

        btnExtenPanelOff.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnExtenPanelOff.setForeground(java.awt.Color.white);
        btnExtenPanelOff.setText("x");
        btnExtenPanelOff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        adminLibros.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        adminLibros.setForeground(new java.awt.Color(204, 204, 204));
        adminLibros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminLibros.setText("Administrar libros");
        adminLibros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        addLibros.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        addLibros.setForeground(java.awt.Color.white);
        addLibros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addLibros.setText("Añadir libros");
        addLibros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        adminUsuarios.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        adminUsuarios.setForeground(java.awt.Color.white);
        adminUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminUsuarios.setText("Administrar usuarios");
        adminUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        prestamos.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        prestamos.setForeground(java.awt.Color.white);
        prestamos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prestamos.setText("Ver prestamos");
        prestamos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        multas.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        multas.setForeground(java.awt.Color.white);
        multas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        multas.setText("Ver Multas");
        multas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        reportes.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        reportes.setForeground(java.awt.Color.white);
        reportes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reportes.setText("Reportes");
        reportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnCerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon("C:\\Users\\Eduar Xavier\\Desktop\\EduarXavier\\sigeli\\Sigeli\\src\\main\\java\\main\\java\\com\\mycompany\\sigeliapp\\vistas\\iconos\\logout.png")); // NOI18N
        btnCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelExtenLayout = new javax.swing.GroupLayout(panelExten);
        panelExten.setLayout(panelExtenLayout);
        panelExtenLayout.setHorizontalGroup(
            panelExtenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelExtenLayout.createSequentialGroup()
                .addContainerGap(176, Short.MAX_VALUE)
                .addComponent(btnExtenPanelOff)
                .addGap(16, 16, 16))
            .addGroup(panelExtenLayout.createSequentialGroup()
                .addGroup(panelExtenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelExtenLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(txtNombrePersona1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelExtenLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(btnOpcionesPanelAdmin1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panelExtenLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelExtenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(multas, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reportes, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
            .addGroup(panelExtenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelExtenLayout.setVerticalGroup(
            panelExtenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExtenLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(btnExtenPanelOff)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOpcionesPanelAdmin1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNombrePersona1, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                .addGap(35, 35, 35)
                .addComponent(adminLibros)
                .addGap(18, 18, 18)
                .addComponent(adminUsuarios)
                .addGap(18, 18, 18)
                .addComponent(addLibros)
                .addGap(18, 18, 18)
                .addComponent(prestamos)
                .addGap(18, 18, 18)
                .addComponent(multas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reportes)
                .addGap(267, 267, 267)
                .addComponent(btnCerrarSesion)
                .addContainerGap())
        );

        getContentPane().add(panelExten, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 650));

        btnVolverMenu.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnVolverMenu.setForeground(new java.awt.Color(51, 51, 51));
        btnVolverMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnVolverMenu.setText("<  Volver");
        btnVolverMenu.setToolTipText("");
        btnVolverMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btnVolverMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 80, -1));

        txtNombrePersona.setBackground(new java.awt.Color(204, 204, 204));
        txtNombrePersona.setForeground(new java.awt.Color(204, 204, 204));
        txtNombrePersona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNombrePersona.setText("jLabel1");
        getContentPane().add(txtNombrePersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 80, -1));

        btnExtenPanel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnExtenPanel.setForeground(new java.awt.Color(255, 255, 255));
        btnExtenPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnExtenPanel.setText(">");
        btnExtenPanel.setToolTipText(">");
        btnExtenPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btnExtenPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, 80, -1));

        btnOpcionesPanelAdmin.setIcon(new javax.swing.ImageIcon("C:\\Users\\Eduar Xavier\\Desktop\\EduarXavier\\sigeli\\Sigeli\\src\\main\\java\\main\\java\\com\\mycompany\\sigeliapp\\vistas\\iconos\\iconoUsuario.png")); // NOI18N
        getContentPane().add(btnOpcionesPanelAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 40, 50));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Añadir un libro");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 270, -1));

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Año");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, 40, -1));

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Fila");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 440, 70, -1));

        txtFila.setEditable(false);
        txtFila.setBackground(new java.awt.Color(249, 249, 249));
        txtFila.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtFila.setForeground(new java.awt.Color(102, 102, 102));
        txtFila.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        txtFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFilaActionPerformed(evt);
            }
        });
        getContentPane().add(txtFila, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 460, 260, 40));

        txtEstante.setEditable(false);
        txtEstante.setBackground(new java.awt.Color(249, 249, 249));
        txtEstante.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtEstante.setForeground(new java.awt.Color(102, 102, 102));
        txtEstante.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        txtEstante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstanteActionPerformed(evt);
            }
        });
        getContentPane().add(txtEstante, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, 260, 40));

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Edición");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 60, -1));

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Estante");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, 70, -1));

        txtAno.setEditable(false);
        txtAno.setBackground(new java.awt.Color(249, 249, 249));
        txtAno.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtAno.setForeground(new java.awt.Color(102, 102, 102));
        txtAno.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        txtAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnoActionPerformed(evt);
            }
        });
        getContentPane().add(txtAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 380, 260, 40));

        txtNombreLibro.setEditable(false);
        txtNombreLibro.setBackground(new java.awt.Color(249, 249, 249));
        txtNombreLibro.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtNombreLibro.setForeground(new java.awt.Color(102, 102, 102));
        txtNombreLibro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        txtNombreLibro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtNombreLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreLibroActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombreLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 550, 40));

        txtEdicion.setEditable(false);
        txtEdicion.setBackground(new java.awt.Color(249, 249, 249));
        txtEdicion.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtEdicion.setForeground(new java.awt.Color(102, 102, 102));
        txtEdicion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        txtEdicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdicionActionPerformed(evt);
            }
        });
        getContentPane().add(txtEdicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 260, 40));

        txtAutor.setEditable(false);
        txtAutor.setBackground(new java.awt.Color(249, 249, 249));
        txtAutor.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtAutor.setForeground(new java.awt.Color(102, 102, 102));
        txtAutor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        txtAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAutorActionPerformed(evt);
            }
        });
        getContentPane().add(txtAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 550, 40));

        txtIsbn.setEditable(false);
        txtIsbn.setBackground(new java.awt.Color(249, 249, 249));
        txtIsbn.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtIsbn.setForeground(new java.awt.Color(102, 102, 102));
        txtIsbn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        txtIsbn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtIsbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIsbnActionPerformed(evt);
            }
        });
        getContentPane().add(txtIsbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 550, 40));

        btnAddlibro.setBackground(new java.awt.Color(249, 249, 249));
        btnAddlibro.setForeground(new java.awt.Color(51, 51, 51));
        btnAddlibro.setText("Crear libro");
        btnAddlibro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 0), 2, true));
        btnAddlibro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddlibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddlibroActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddlibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 550, 210, 30));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Nombre del libro");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 140, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("ISBN");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 140, -1));

        txtCarreraTxt.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtCarreraTxt.setForeground(new java.awt.Color(51, 51, 51));
        txtCarreraTxt.setText("Autor");
        getContentPane().add(txtCarreraTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 240, -1));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Eduar Xavier\\Desktop\\EduarXavier\\sigeli\\Sigeli\\src\\main\\java\\main\\java\\com\\mycompany\\sigeliapp\\vistas\\imagenes\\interfazPaneles.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreLibroActionPerformed

    private void txtIsbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIsbnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIsbnActionPerformed

    private void btnAddlibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddlibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddlibroActionPerformed

    private void txtEdicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdicionActionPerformed

    private void txtAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAutorActionPerformed

    private void txtAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnoActionPerformed

    private void txtFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFilaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFilaActionPerformed

    private void txtEstanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstanteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelAddLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelAddLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelAddLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelAddLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelAddLibro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel addLibros;
    public javax.swing.JLabel adminLibros;
    public javax.swing.JLabel adminUsuarios;
    public javax.swing.JButton btnAddlibro;
    public javax.swing.JLabel btnCerrarSesion;
    public javax.swing.JLabel btnExtenPanel;
    public javax.swing.JLabel btnExtenPanelOff;
    public javax.swing.JLabel btnOpcionesPanelAdmin;
    public javax.swing.JLabel btnOpcionesPanelAdmin1;
    public javax.swing.JLabel btnVolverMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel multas;
    public javax.swing.JPanel panelExten;
    public javax.swing.JLabel prestamos;
    public javax.swing.JLabel reportes;
    public javax.swing.JTextField txtAno;
    public javax.swing.JTextField txtAutor;
    public javax.swing.JLabel txtCarreraTxt;
    public javax.swing.JTextField txtEdicion;
    public javax.swing.JTextField txtEstante;
    public javax.swing.JTextField txtFila;
    public javax.swing.JTextField txtIsbn;
    public javax.swing.JTextField txtNombreLibro;
    public javax.swing.JLabel txtNombrePersona;
    public javax.swing.JLabel txtNombrePersona1;
    // End of variables declaration//GEN-END:variables
}
