/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.java.com.mycompany.sigeliapp.vistas;

/**
 *
 * @author Eduar Xavier
 */
public class PanelReportes extends javax.swing.JFrame {

    /**
     * Creates new form PanelVistaLibro
     */
    public PanelReportes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        panelExten = new javax.swing.JPanel();
        btnOpcionesPanelAdmin1 = new javax.swing.JLabel();
        txtNombrePersona1 = new javax.swing.JLabel();
        btnExtenPanelOff = new javax.swing.JLabel();
        adminLibros = new javax.swing.JLabel();
        addLibros = new javax.swing.JLabel();
        adminUsuarios = new javax.swing.JLabel();
        prestamos = new javax.swing.JLabel();
        multas = new javax.swing.JLabel();
        reportes = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JLabel();
        btnVolverMenu = new javax.swing.JLabel();
        txtNombrePersona = new javax.swing.JLabel();
        btnIncluirTodo = new javax.swing.JRadioButton();
        btnExtenPanel = new javax.swing.JLabel();
        btnOpcionesPanelAdmin = new javax.swing.JLabel();
        txtMesFin = new javax.swing.JComboBox<>();
        txtMesInicio = new javax.swing.JComboBox<>();
        txtDiaInicio = new javax.swing.JTextField();
        btnPagos = new javax.swing.JRadioButton();
        btnPrestamos = new javax.swing.JRadioButton();
        btnMultas = new javax.swing.JRadioButton();
        txtCarreraTxt1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservaciones = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtAnoInicio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtAnoFin = new javax.swing.JTextField();
        txtDiaFin = new javax.swing.JTextField();
        btnCrearReporte = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCarreraTxt = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Eduar Xavier\\Desktop\\EduarXavier\\sigeli\\Sigeli\\src\\main\\java\\main\\java\\com\\mycompany\\sigeliapp\\vistas\\iconos\\inconoCopiar.png")); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelExten.setBackground(new java.awt.Color(126, 0, 0));

        btnOpcionesPanelAdmin1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Eduar Xavier\\Desktop\\EduarXavier\\sigeli\\Sigeli\\src\\main\\java\\main\\java\\com\\mycompany\\sigeliapp\\vistas\\iconos\\iconoUsuario.png")); // NOI18N
        btnOpcionesPanelAdmin1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtNombrePersona1.setBackground(new java.awt.Color(204, 204, 204));
        txtNombrePersona1.setForeground(java.awt.Color.white);
        txtNombrePersona1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNombrePersona1.setText("jLabel1");

        btnExtenPanelOff.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnExtenPanelOff.setForeground(java.awt.Color.white);
        btnExtenPanelOff.setText("x");
        btnExtenPanelOff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        adminLibros.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        adminLibros.setForeground(new java.awt.Color(204, 204, 204));
        adminLibros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminLibros.setText("Administrar libros");
        adminLibros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        addLibros.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        addLibros.setForeground(java.awt.Color.white);
        addLibros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addLibros.setText("Añadir libros");
        addLibros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        adminUsuarios.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        adminUsuarios.setForeground(java.awt.Color.white);
        adminUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminUsuarios.setText("Administrar usuarios");
        adminUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        prestamos.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        prestamos.setForeground(java.awt.Color.white);
        prestamos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prestamos.setText("Ver prestamos");
        prestamos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        multas.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        multas.setForeground(java.awt.Color.white);
        multas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        multas.setText("Ver Multas");
        multas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        reportes.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        reportes.setForeground(java.awt.Color.white);
        reportes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reportes.setText("Reportes");
        reportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnCerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon("C:\\Users\\Eduar Xavier\\Desktop\\EduarXavier\\sigeli\\Sigeli\\src\\main\\java\\main\\java\\com\\mycompany\\sigeliapp\\vistas\\iconos\\logout.png")); // NOI18N
        btnCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelExtenLayout = new javax.swing.GroupLayout(panelExten);
        panelExten.setLayout(panelExtenLayout);
        panelExtenLayout.setHorizontalGroup(
            panelExtenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelExtenLayout.createSequentialGroup()
                .addContainerGap(176, Short.MAX_VALUE)
                .addComponent(btnExtenPanelOff)
                .addGap(16, 16, 16))
            .addGroup(panelExtenLayout.createSequentialGroup()
                .addGroup(panelExtenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelExtenLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(txtNombrePersona1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelExtenLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(btnOpcionesPanelAdmin1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panelExtenLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelExtenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(multas, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reportes, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
            .addGroup(panelExtenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelExtenLayout.setVerticalGroup(
            panelExtenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExtenLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(btnExtenPanelOff)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOpcionesPanelAdmin1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNombrePersona1, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                .addGap(35, 35, 35)
                .addComponent(adminLibros)
                .addGap(18, 18, 18)
                .addComponent(adminUsuarios)
                .addGap(18, 18, 18)
                .addComponent(addLibros)
                .addGap(18, 18, 18)
                .addComponent(prestamos)
                .addGap(18, 18, 18)
                .addComponent(multas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reportes)
                .addGap(267, 267, 267)
                .addComponent(btnCerrarSesion)
                .addContainerGap())
        );

        getContentPane().add(panelExten, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 650));

        btnVolverMenu.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnVolverMenu.setForeground(new java.awt.Color(51, 51, 51));
        btnVolverMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnVolverMenu.setText("<  Volver");
        btnVolverMenu.setToolTipText("");
        btnVolverMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btnVolverMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 80, -1));

        txtNombrePersona.setBackground(new java.awt.Color(204, 204, 204));
        txtNombrePersona.setForeground(new java.awt.Color(204, 204, 204));
        txtNombrePersona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNombrePersona.setText("jLabel1");
        getContentPane().add(txtNombrePersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 80, -1));

        btnIncluirTodo.setForeground(new java.awt.Color(51, 51, 51));
        btnIncluirTodo.setText("Incluir todo");
        btnIncluirTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirTodoActionPerformed(evt);
            }
        });
        getContentPane().add(btnIncluirTodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 480, -1, -1));

        btnExtenPanel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnExtenPanel.setForeground(new java.awt.Color(255, 255, 255));
        btnExtenPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnExtenPanel.setText(">");
        btnExtenPanel.setToolTipText(">");
        btnExtenPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btnExtenPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, 80, -1));

        btnOpcionesPanelAdmin.setIcon(new javax.swing.ImageIcon("C:\\Users\\Eduar Xavier\\Desktop\\EduarXavier\\sigeli\\Sigeli\\src\\main\\java\\main\\java\\com\\mycompany\\sigeliapp\\vistas\\iconos\\iconoUsuario.png")); // NOI18N
        getContentPane().add(btnOpcionesPanelAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 40, 50));

        txtMesFin.setBackground(new java.awt.Color(249, 249, 249));
        txtMesFin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(txtMesFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 150, 40));

        txtMesInicio.setBackground(new java.awt.Color(249, 249, 249));
        txtMesInicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(txtMesInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 150, 40));

        txtDiaInicio.setBackground(new java.awt.Color(249, 249, 249));
        txtDiaInicio.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtDiaInicio.setForeground(new java.awt.Color(102, 102, 102));
        txtDiaInicio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        txtDiaInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtDiaInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaInicioActionPerformed(evt);
            }
        });
        getContentPane().add(txtDiaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 150, 40));

        btnPagos.setForeground(new java.awt.Color(51, 51, 51));
        btnPagos.setText("Pagos");
        btnPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagosActionPerformed(evt);
            }
        });
        getContentPane().add(btnPagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, -1, -1));

        btnPrestamos.setForeground(new java.awt.Color(51, 51, 51));
        btnPrestamos.setText("Prestamos");
        getContentPane().add(btnPrestamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, -1, -1));

        btnMultas.setForeground(new java.awt.Color(51, 51, 51));
        btnMultas.setText("Multas");
        btnMultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultasActionPerformed(evt);
            }
        });
        getContentPane().add(btnMultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, -1, -1));

        txtCarreraTxt1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtCarreraTxt1.setForeground(new java.awt.Color(51, 51, 51));
        txtCarreraTxt1.setText("Observaciones");
        getContentPane().add(txtCarreraTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, 110, -1));

        txtObservaciones.setBackground(new java.awt.Color(249, 249, 249));
        txtObservaciones.setColumns(20);
        txtObservaciones.setRows(5);
        txtObservaciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        txtObservaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(txtObservaciones);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, 400, 190));

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("DIA");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 40, -1));

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("MES");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, 40, -1));

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("AÑO");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 160, 40, -1));

        txtAnoInicio.setBackground(new java.awt.Color(249, 249, 249));
        txtAnoInicio.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtAnoInicio.setForeground(new java.awt.Color(102, 102, 102));
        txtAnoInicio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        txtAnoInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtAnoInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnoInicioActionPerformed(evt);
            }
        });
        getContentPane().add(txtAnoInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 150, 140, 40));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Administración de reportes");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 420, -1));

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("AÑO");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 260, 40, -1));

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("DIA");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 40, -1));

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("MES");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, 40, -1));

        txtAnoFin.setBackground(new java.awt.Color(249, 249, 249));
        txtAnoFin.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtAnoFin.setForeground(new java.awt.Color(102, 102, 102));
        txtAnoFin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        txtAnoFin.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtAnoFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnoFinActionPerformed(evt);
            }
        });
        getContentPane().add(txtAnoFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 250, 140, 40));

        txtDiaFin.setBackground(new java.awt.Color(249, 249, 249));
        txtDiaFin.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtDiaFin.setForeground(new java.awt.Color(102, 102, 102));
        txtDiaFin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        txtDiaFin.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtDiaFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaFinActionPerformed(evt);
            }
        });
        getContentPane().add(txtDiaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 150, 40));

        btnCrearReporte.setBackground(new java.awt.Color(249, 249, 249));
        btnCrearReporte.setForeground(new java.awt.Color(51, 51, 51));
        btnCrearReporte.setText("Generar reporte");
        btnCrearReporte.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 0), 2, true));
        btnCrearReporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrearReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearReporteActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrearReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 570, 210, 30));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Fecha de inicio");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 140, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Fecha final");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 140, -1));

        txtCarreraTxt.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtCarreraTxt.setForeground(new java.awt.Color(51, 51, 51));
        txtCarreraTxt.setText("Elegir reporte");
        getContentPane().add(txtCarreraTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 110, -1));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Eduar Xavier\\Desktop\\EduarXavier\\sigeli\\Sigeli\\src\\main\\java\\main\\java\\com\\mycompany\\sigeliapp\\vistas\\imagenes\\interfazPaneles.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearReporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearReporteActionPerformed

    private void txtDiaFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaFinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaFinActionPerformed

    private void txtAnoFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnoFinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnoFinActionPerformed

    private void txtDiaInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaInicioActionPerformed

    private void txtAnoInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnoInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnoInicioActionPerformed

    private void btnMultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMultasActionPerformed

    private void btnPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPagosActionPerformed

    private void btnIncluirTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirTodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIncluirTodoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelReportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel addLibros;
    public javax.swing.JLabel adminLibros;
    public javax.swing.JLabel adminUsuarios;
    public javax.swing.JLabel btnCerrarSesion;
    public javax.swing.JButton btnCrearReporte;
    public javax.swing.JLabel btnExtenPanel;
    public javax.swing.JLabel btnExtenPanelOff;
    public javax.swing.JRadioButton btnIncluirTodo;
    public javax.swing.JRadioButton btnMultas;
    public javax.swing.JLabel btnOpcionesPanelAdmin;
    public javax.swing.JLabel btnOpcionesPanelAdmin1;
    public javax.swing.JRadioButton btnPagos;
    public javax.swing.JRadioButton btnPrestamos;
    public javax.swing.JLabel btnVolverMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel multas;
    public javax.swing.JPanel panelExten;
    public javax.swing.JLabel prestamos;
    public javax.swing.JLabel reportes;
    public javax.swing.JTextField txtAnoFin;
    public javax.swing.JTextField txtAnoInicio;
    public javax.swing.JLabel txtCarreraTxt;
    public javax.swing.JLabel txtCarreraTxt1;
    public javax.swing.JTextField txtDiaFin;
    public javax.swing.JTextField txtDiaInicio;
    public javax.swing.JComboBox<String> txtMesFin;
    public javax.swing.JComboBox<String> txtMesInicio;
    public javax.swing.JLabel txtNombrePersona;
    public javax.swing.JLabel txtNombrePersona1;
    public javax.swing.JTextArea txtObservaciones;
    // End of variables declaration//GEN-END:variables
}
